[build]
builder = "dockerfile"
dockerfilePath = "./WeatherDashboardBackend/Dockerfile"

[deploy]
startCommand = "dotnet WeatherDashboardBackend.dll"
restartPolicyType = "always"
healthcheckPath = "/health"
